<?php

namespace Yannick\CrudBundle\Repository;

/**
 * DepartementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementsRepository extends \Doctrine\ORM\EntityRepository
{

	public function getLikeQueryBuilder($pattern)
  {
    return $this
      ->createQueryBuilder('d')
      ->where('d.nom LIKE :pattern')
      ->setParameter('pattern', $pattern)
    ;
  }

    public function myFindAll()
{
    $queryBuilder = $this->createQueryBuilder('a');
    // On n'ajoute pas de critère ou tri particulier, la construction
    // de notre requête est finie
    // On récupère la Query à partir du QueryBuilder
    $query = $queryBuilder->getQuery();
    // On récupère les résultats à partir de la Query
    $results = $query->getResult();
    // On retourne ces résultats
    return $results;
  }

}
